packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/cli": 1.4.0-beta.9
  "@better-auth/expo": 1.4.0-beta.9
  "@eslint/js": ^9.38.0
  "@prisma/client": ^6.19.0
  "@t3-oss/env-core": ^0.13.8
  "@t3-oss/env-nextjs": ^0.13.8
  "@tailwindcss/postcss": ^4.1.16
  "@tailwindcss/vite": ^4.1.16
  "@tanstack/react-form": ^1.23.8
  "@tanstack/react-query": ^5.90.8
  "@trpc/client": ^11.7.1
  "@trpc/server": ^11.7.1
  "@trpc/tanstack-react-query": ^11.7.1
  "@types/node": ^22.18.12
  "@vitejs/plugin-react": 5.1.0
  better-auth: 1.4.0-beta.9
  eslint: ^9.38.0
  i18next: ^25.8.0
  jiti: ^2.5.1
  next: ^16.0.9
  next-intl: ^4.7.0
  prettier: ^3.6.2
  prisma: ^6.19.0
  react-i18next: ^16.5.3
  superjson: 2.2.3
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  zod: ^4.1.12
  vite: 7.1.12

catalogs:
  react19:
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
    react: 19.1.4
    react-dom: 19.1.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  lightningcss: 1.30.1
  vite: 7.1.12

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
